### PR TITLE
resolved the error in page.tsx of speaker

### PR DESCRIPTION
**Pull request by TheJayas**
An error was coming when try to render page.tsx/speaker ->
" 
understand the whole code and tell me reason of the error " ⨯ PrismaClientKnownRequestError: 
Invalid `prisma.keytalk.findUnique()` invocation:
Inconsistent column data: Failed to convert 'DateTime("2024-03-26 18:30:00.0 +00:00:00")' to 'String' for the field 'time'.
    at async assignTitles (./src/app/admin/speakers/page.tsx:28:34)
    at async SpeakerAdminPage (./src/app/admin/speakers/page.tsx:43:28)
"
It is resolved with this pull request.

### CODE REVIEW

**Comment by piyush-panpaliya** [comment]
Correct schema for that table is on dev branch
DB has type of DateTime for time column
but on master schema it has type string thus giving the err.

Please sync your dev branch and build features from that branch and keep master only for production code and allow PR only from dev for new release

**Comment by rajatverma311201** [comment]
@piyush-panpaliya dev is my personal branch and it is not to be used

**Comment by rajatverma311201** [comment]
I will rename it if it is misleading

**Comment by TheJayas** [comment]
Is this PR needed?

**Pull request merged**
